USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MOVIELENS;
USE SCHEMA DEV;

SELECT * FROM MOVIELENS.DEV.FCT_RATINGS ORDER BY RATING_TIMESTAMP DESC LIMIT 5;

-- MAX RATING_TIMESTAMP AVAILABLE - 2015-03-30 23:40:02.000 -0700

SELECT * FROM MOVIELENS.DEV.STG_RATINGS ORDER BY RATING_TIMESTAMP DESC LIMIT 5;

--SHOW WAREHOUSES;
INSERT INTO MOVIELENS.DEV.STG_RATINGS (USER_ID, MOVIE_ID, RATING, RATING_TIMESTAMP)
VALUES (87587, '7151', '4.0', '2015-03-31 23:40:02.000 -0700');


-- Testing Sanpshots
-- SNAP_TAGS Testing
SELECT * FROM SNAPSHOTS.SNAP_TAGS
ORDER BY USER_ID, DBT_VALID_FROM DESC;

-- UPDATE IN STG_TAGS - SRC OF SNAP_TAGS
UPDATE DEV.STG_TAGS
SET TAG = 'Mark Waters Returns', TAG_TIMESTAMP = CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ)
WHERE USER_ID = 18;

SELECT * FROM DEV.STG_TAGS
WHERE USER_ID=18;

-- Check after running sanpshot again
SELECT * FROM SNAPSHOTS.SNAP_TAGS
WHERE USER_ID=18;