-- Use Admin role
USE ROLE ACCOUNTADMIN;

-- Create 'transform' role and assign it to AccountAdmin
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Create 'dbt' user and assign transform role
CREATE USER IF NOT EXISTS dbt
PASSWORD='dbtPassword@123'
LOGIN_NAME='dbt'
MUST_CHANGE_PASSWORD=FALSE
DEFAULT_WAREHOUSE='COMPUTE_WH'
DEFAULT_ROLE=TRANSFORM
DEFAULT_NAMESPACE='MOVIELENS_RAW'
COMMENT='DBT user for data transformation';

-- Change user type of the Snowflake user dbt to LEGACY_SERVICE.
-- LEGACY_SERVICE users are meant for non-interactive service accounts (e.g., dbt, Airflow, automated ETL jobs)
ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt;

-- Create DB & Schema
CREATE DATABASE IF NOT EXISTS MOVIELENS;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.RAW;

-- Grant permissions to transform role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;

-- Setting autosuspend to 60 to reduce cost
ALTER WAREHOUSE COMPUTE_WH SET AUTO_SUSPEND=60;

SHOW WAREHOUSES;

--SELECT CURRENT_ACCOUNT(), CURRENT_REGION();

-- Create File Format
CREATE OR REPLACE FILE FORMAT NETFLIX_FF
TYPE=CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

-- Create Internal Stage
CREATE OR REPLACE STAGE NETFLIX_STAGE
FILE_FORMAT=NETFLIX_FF;

-- #############################
-- TABLE CREATION & DATA LOADING
-- #############################

--ls @NETFLIX_STAGE;

-- Genome Scores Table
CREATE OR REPLACE TABLE RAW_GENOME_SCORES(
      movieId INTEGER,
      tagId INTEGER,
      relevance FLOAT
);

COPY INTO RAW_GENOME_SCORES
FROM '@netflix_stage/genome-scores.csv'
FILE_FORMAT=NETFLIX_FF;

-- Genome Tags Table
CREATE OR REPLACE TABLE RAW_GENOME_TAGS(
    tagId INTEGER,
    tag STRING
);

COPY INTO RAW_GENOME_TAGS
FROM '@netflix_stage/genome-tags.csv'
FILE_FORMAT=NETFLIX_FF;

-- Links Table
CREATE OR REPLACE TABLE RAW_LINKS(
    movieId INTEGER,
    imdbId INTEGER,
    tmdbId INTEGER
);

COPY INTO RAW_LINKS
FROM '@netflix_stage/links.csv'
FILE_FORMAT=NETFLIX_FF;

-- Movies Table
CREATE OR REPLACE TABLE RAW_MOVIES(
    movieId INTEGER,
    title STRING,
    genres STRING
);

-- Load data in movies table from stage
COPY INTO RAW_MOVIES
FROM '@NETFLIX_STAGE/movies.csv'
FILE_FORMAT=NETFLIX_FF;

--SELECT * FROM RAW_MOVIES;

-- Ratings Table
CREATE OR REPLACE TABLE RAW_RATINGS (
    userId INTEGER,
    movieId INTEGER,
    rating FLOAT,
    "timestamp" BIGINT 
);

COPY INTO RAW_RATINGS
FROM '@netflix_stage/ratings.csv';

-- Tags Table
CREATE OR REPLACE TABLE RAW_TAGS(
    userId INTEGER,
    movieId INTEGER,
    "tag" STRING,
    "timestamp" BIGINT
);

COPY INTO RAW_TAGS
FROM '@netflix_stage/tags.csv'
FILE_FORMAT=NETFLIX_FF
ON_ERROR = 'CONTINUE';




