WITH RATINGS AS (
    SELECT DISTINCT USER_ID FROM {{ ref('stg_ratings') }}
),
TAGS AS (
    SELECT DISTINCT USER_ID FROM {{ ref('stg_tags') }}
)

SELECT
    DISTINCT USER_ID
FROM
(
    SELECT USER_ID FROM RATINGS
    UNION
    SELECT USER_ID FROM TAGS
)
